name: Push Docker image
description: Push Docker image

inputs:
  username:
    description: Docker repository username
    required: true
  password:
    description: Docker repository password
    required: true
  repository:
    description: Docker repository name
    required: false
    default: kubasejdak
  image:
    description: Docker image name
    required: true
  tag:
    description: Docker image tag
    required: true

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.image }}-${{ inputs.tag }}
    - name: docker load
      shell: bash
      run: |
        docker load -i ${{ inputs.image }}-${{ inputs.tag }}
        rm ${{ inputs.image }}-${{ inputs.tag }}
    - name: docker login
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: docker push
      shell: bash
      run: docker push ${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag }}
